cd Barstow_1891/; ./make_all.sh ; cd ..
cd Barstow_1892/; ./make_all.sh ; cd ..
cd Barstow_1893/; ./make_all.sh ; cd ..
cd Baylies_1887/; ./make_all.sh ; cd ..
cd Baylies_1888/; ./make_all.sh ; cd ..
cd Baylies_1889/; ./make_all.sh ; cd ..
cd Baylies_1890/; ./make_all.sh ; cd ..
cd Baylies_1891/; ./make_all.sh ; cd ..
cd Baylies_1892/; ./make_all.sh ; cd ..
cd Beluga_1893a/; ./make_all.sh ; cd ..
cd Beluga_1893b/; ./make_all.sh ; cd ..
cd Beluga_1893c/; ./make_all.sh ; cd ..
cd Beluga_1900a/; ./make_all.sh ; cd ..
cd Beluga_1900b/; ./make_all.sh ; cd ..
cd Beluga_1902a/; ./make_all.sh ; cd ..
cd Beluga_1902b/; ./make_all.sh ; cd ..
cd Belvedere_1894/; ./make_all.sh ; cd ..
cd Belvedere_1904/; ./make_all.sh ; cd ..
cd California_1892/; ./make_all.sh ; cd ..
cd California_1893/; ./make_all.sh ; cd ..
cd Monterey_1905/; ./make_all.sh ; cd ..
cd William_Baylies_1899/; ./make_all.sh ; cd ..
cd William_Baylies_1900a/; ./make_all.sh ; cd ..
cd William_Baylies_1900b/; ./make_all.sh ; cd ..
cd William_Baylies_1901/; ./make_all.sh ; cd ..
