cd Barstow_1891/; R --no-save < build_manifest_scribe.R ; cd ..
cd Barstow_1892/; R --no-save < build_manifest_scribe.R ; cd ..
cd Barstow_1893/; R --no-save < build_manifest_scribe.R ; cd ..
cd Baylies_1887/; R --no-save < build_manifest_scribe.R ; cd ..
cd Baylies_1888/; R --no-save < build_manifest_scribe.R ; cd ..
cd Baylies_1889/; R --no-save < build_manifest_scribe.R ; cd ..
cd Baylies_1890/; R --no-save < build_manifest_scribe.R ; cd ..
cd Baylies_1891/; R --no-save < build_manifest_scribe.R ; cd ..
cd Baylies_1892/; R --no-save < build_manifest_scribe.R ; cd ..
cd Beluga_1893a/; R --no-save < build_manifest_scribe.R ; cd ..
cd Beluga_1893b/; R --no-save < build_manifest_scribe.R ; cd ..
cd Beluga_1893c/; R --no-save < build_manifest_scribe.R ; cd ..
cd Beluga_1900a/; R --no-save < build_manifest_scribe.R ; cd ..
cd Beluga_1900b/; R --no-save < build_manifest_scribe.R ; cd ..
cd Beluga_1902a/; R --no-save < build_manifest_scribe.R ; cd ..
cd Beluga_1902b/; R --no-save < build_manifest_scribe.R ; cd ..
cd Belvedere_1894/; R --no-save < build_manifest_scribe.R ; cd ..
cd Belvedere_1904/; R --no-save < build_manifest_scribe.R ; cd ..
cd California_1892/; R --no-save < build_manifest_scribe.R ; cd ..
cd California_1893/; R --no-save < build_manifest_scribe.R ; cd ..
cd Monterey_1905/; R --no-save < build_manifest_scribe.R ; cd ..
cd William_Baylies_1899/; R --no-save < build_manifest_scribe.R ; cd ..
cd William_Baylies_1900a/; R --no-save < build_manifest_scribe.R ; cd ..
cd William_Baylies_1900b/; R --no-save < build_manifest_scribe.R ; cd ..
cd William_Baylies_1901/; R --no-save < build_manifest_scribe.R ; cd ..
